### PR TITLE
silly tag in introducton

### PR DESCRIPTION
**Pull request by remcmurry**
Hi i think this is right .. do you see my change?  took me a day to get back to it but I think i finally got it.  Cheers feel freet o not accept my egotistical edit.   thanks for the intro .. i saved the cmd session to look at again later ... what was the command to start a new environment again?

### CODE REVIEW

**Comment by moorepants** [comment]
Yes I see it. You've successfully made your first pull request on Github!

On Windows, to activate an environment:

```
activate myenv
```

And to deactivate:

```
deactivate
```

**Comment by moorepants** [comment]
For more info on using conda:

http://conda.pydata.org/docs/

**Comment by moorepants** [comment]
Oh, to start a new environment:

```
conda create -n mynewenv numpy=1.9 scipy=0.12 spyder
```

**Comment by remcmurry** [comment]
thanks that was missed in the copy of the command window text

Cheers

Robert (Robbie) McMurry
Assistant Development Engineer, Western Cooling Efficiency Center
Minister, Davis Bike Collective (Bike Forth)
remcmurry@gmail.com
mobile: (575) 323 4561

**Pull request closed without merging**
